/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as attackSol from "./Attack.sol";
export type { attackSol };
import type * as grantsQuerySol from "./GrantsQuery.sol";
export type { grantsQuerySol };
export type { ERC20 } from "./ERC20";
export type { Grant } from "./Grant";
export type { GrantFactory } from "./GrantFactory";
export type { GrantFunder } from "./GrantFunder";
export type { Market } from "./Market";
export type { MarketEdited } from "./MarketEdited";
export type { MarketTest } from "./MarketTest";
export type { MockVault } from "./MockVault";
