/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GrantFactory__factory } from "./GrantFactory__factory";
export { GrantFunderFactory__factory } from "./GrantFunderFactory__factory";
