/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GrantsQuery__factory } from "./GrantsQuery__factory";
export { IGrant__factory } from "./IGrant__factory";
export { IGrantFactory__factory } from "./IGrantFactory__factory";
