/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export declare namespace GrantsQuery {
  export type GrantStructStruct = {
    grantId: PromiseOrValue<BigNumberish>;
    recipient: PromiseOrValue<string>;
    tokenAddress: PromiseOrValue<string>;
    timestamp: PromiseOrValue<BigNumberish>;
    balance: PromiseOrValue<BigNumberish>;
    grantAddress: PromiseOrValue<string>;
  };

  export type GrantStructStructOutput = [
    BigNumber,
    string,
    string,
    BigNumber,
    BigNumber,
    string
  ] & {
    grantId: BigNumber;
    recipient: string;
    tokenAddress: string;
    timestamp: BigNumber;
    balance: BigNumber;
    grantAddress: string;
  };
}

export interface GrantsQueryInterface extends utils.Interface {
  functions: {
    "getAllGrants()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "getAllGrants"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "getAllGrants",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "getAllGrants",
    data: BytesLike
  ): Result;

  events: {};
}

export interface GrantsQuery extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: GrantsQueryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getAllGrants(
      overrides?: CallOverrides
    ): Promise<
      [GrantsQuery.GrantStructStructOutput[]] & {
        allData: GrantsQuery.GrantStructStructOutput[];
      }
    >;
  };

  getAllGrants(
    overrides?: CallOverrides
  ): Promise<GrantsQuery.GrantStructStructOutput[]>;

  callStatic: {
    getAllGrants(
      overrides?: CallOverrides
    ): Promise<GrantsQuery.GrantStructStructOutput[]>;
  };

  filters: {};

  estimateGas: {
    getAllGrants(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getAllGrants(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
