/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GrantsQuery } from "./GrantsQuery";
export type { IGrant } from "./IGrant";
export type { IGrantFactory } from "./IGrantFactory";
