/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { GrantFactory } from "./GrantFactory";
export type { GrantFunderFactory } from "./GrantFunderFactory";
